### PR TITLE
Do not parse ls output for file listings

### PR DESCRIPTION
**Pull request by jjatria**
If #23 is a problem with the `ls` command, which might not be present or might produce different output in a non-English locale, then the most obvious solution is to stop relying on `ls` output (which is in general [a good idea][1]).

Since AnyEvent::FTP already depends on Path::Class, which provides a `children` method which gives the necessary file listing, this patch replaces one with the other to solve the issue.

[1]: https://unix.stackexchange.com/questions/128985/why-not-parse-ls

### CODE REVIEW

**Comment by plicease** [comment]
We need to reproduce the behavior of `ls -l` for a long listing (little l).  This gives you the equivalent of `ls -1` (one)

**Comment by jjatria** [comment]
Oh, I see the difference.

As a possible solution you suggested bundling `ls` from PerlPowerTools, which as far as I cna tell is a self-contained script. How would that bundling work?

**Comment by plicease** [comment]
I did something similar once for App::RegexFileUtils.  I put the scripts in a share directory:

https://github.com/plicease/App-RegexFileUtils/tree/master/share/ppt

The POD in AnyEvent::FTP should mention that the file is bundled and what the license is.  Something like this.

https://github.com/plicease/App-RegexFileUtils/blob/master/lib/App/RegexFileUtils.pm#L93

Should do some basic checking that ppt version of ls doesn't introduce any new non-core deps for Perl 5.8-5.26 (I am pretty sure that it doesn't).  Or maybe make them required on windows if there are.

Should use $^X to run the script.

**Comment by jjatria** [comment]
Sorry for the extended silence.

I had some trouble bundling the script from the share directory because it wouldn't work while doing a local build (so it was impossible to install the module). I tried following the example you provided, but I couldn't manage to get it to work.

Then I found File::Share, which seems to do this. I pushed some changes that use that module to use the `ls` script from PPT, and they seem to work (I rebased from master to try and keep things a little tidier).

Is adding File::Share as a dependency a problem?

PS: I'm not sure why the AppVeyor tests are failing. Any insights?

**Comment by plicease** [comment]
File::Share is fine.  I will take a look soon.  Thanks!

I have a feeling the appveyor failures have to do with cacheing the wrong DLLs.  This is either my fault or appveyor being hard to use.  Or both.  I can test on windows myself.

**Comment by plicease** [comment]
Merged!  Thanks.  I made only a couple of minor tweaks.  Important one though is using $^X to execute ls.pl.  /usr/bin/perl may not work with the PERL5LIB or whatnot, so we want to make sure we are using the same Perl for ls.pl as we are using for the server.  this will probably fix a number of the windows failures.

**Pull request closed without merging**
